// PoneMarket Paper Trading API - see README.md for usage
const express=require('express'),cors=require('cors'),crypto=require('crypto'),{v4:uuidv4}=require('uuid');
const app=express();
app.use(cors({
  origin: '*',
  methods: ['GET','POST','PUT','DELETE','OPTIONS'],
  allowedHeaders: ['Content-Type','Authorization']
}));
app.options('*', cors());
app.use(express.json());
const DB={agents:{},orders:{},markets:{}};
const SEED=[
  {id:'mkt_gov_shutdown',title:'How long will the Government Shutdown last?',category:'politics',volume:17400000,closes_at:'2026-03-14T23:59:59Z',outcomes:[{id:'out_5d',label:'5+ days',price_yes:0.21,price_no:0.79},{id:'out_6d',label:'6+ days',price_yes:0.07,price_no:0.93}]},
  {id:'mkt_btc_feb',title:'What price will Bitcoin hit in February?',category:'crypto',volume:10000000,closes_at:'2026-02-28T23:59:59Z',outcomes:[{id:'out_95k',label:'↑ $95,000',price_yes:0.12,price_no:0.88},{id:'out_90k',label:'↑ $90,000',price_yes:0.26,price_no:0.74}]},
  {id:'mkt_fed',title:'Fed decision in March?',category:'finance',volume:50000000,closes_at:'2026-03-20T23:59:59Z',outcomes:[{id:'out_cut',label:'Rate Cut',price_yes:0.08,price_no:0.92},{id:'out_hold',label:'Hold',price_yes:0.87,price_no:0.13}]},
  {id:'mkt_ukraine',title:'Russia × Ukraine ceasefire by end of 2026?',category:'geopolitics',volume:8000000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.46,price_no:0.54}]},
  {id:'mkt_oscars',title:'Oscars 2026: Best Picture Winner?',category:'culture',volume:11000000,closes_at:'2026-03-28T23:59:59Z',outcomes:[{id:'out_conclave',label:'Conclave',price_yes:0.69,price_no:0.31},{id:'out_emilia',label:'Emilia Pérez',price_yes:0.18,price_no:0.82}]},
  {id:'mkt_giannis',title:'Where will Giannis be traded?',category:'sports',volume:1000000,closes_at:'2026-02-06T23:59:59Z',outcomes:[{id:'out_heat',label:'Miami Heat',price_yes:0.34,price_no:0.66},{id:'out_warriors',label:'Golden State',price_yes:0.22,price_no:0.78}]},
  {id:'mkt_greenland',title:'Will the US acquire part of Greenland in 2026?',category:'politics',volume:7000000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.20,price_no:0.80}]},
  {id:'mkt_eth',title:'Will Ethereum reach $5,000 in 2025?',category:'crypto',volume:6200000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.44,price_no:0.56}]},
  {id:'mkt_sp500',title:'Will the S&P 500 hit 7,000 in 2025?',category:'finance',volume:11000000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.58,price_no:0.42}]},
  {id:'mkt_gpt5',title:'Will OpenAI release GPT-5 in 2025?',category:'tech',volume:9100000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.78,price_no:0.22}]},
  {id:'mkt_taiwan',title:'Will China invade Taiwan in 2025?',category:'geopolitics',volume:31000000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.09,price_no:0.91}]},
  {id:'mkt_recession',title:'Will the US enter a recession in 2025?',category:'finance',volume:18000000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.34,price_no:0.66}]},
  {id:'mkt_trump',title:'Will Trump be impeached in his second term?',category:'politics',volume:22000000,closes_at:'2029-01-20T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.12,price_no:0.88}]},
  {id:'mkt_doge',title:'Will DOGE cut $1 trillion from US federal spending?',category:'politics',volume:14000000,closes_at:'2026-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.29,price_no:0.71}]},
  {id:'mkt_agi',title:'Will AGI be achieved before 2030?',category:'tech',volume:15000000,closes_at:'2029-12-31T23:59:59Z',outcomes:[{id:'out_yes',label:'Yes',price_yes:0.24,price_no:0.76}]},
];
SEED.forEach(m=>DB.markets[m.id]={...m,status:'active',created_at:new Date().toISOString()});
const apiKey=()=>'pm_live_'+crypto.randomBytes(20).toString('hex');
const auth=(req,res,next)=>{const h=req.headers['authorization'];if(!h?.startsWith('Bearer '))return res.status(401).json({error:{code:401,type:'UNAUTHORIZED',message:'Missing Authorization header.'}});const ag=Object.values(DB.agents).find(a=>a.api_key===h.split(' ')[1]);if(!ag)return res.status(401).json({error:{code:401,type:'UNAUTHORIZED',message:'Invalid API key.'}});req.agent=ag;next();};
const impact=(out,side,amt)=>{const d=Math.min(amt/50000,0.05);out.price_yes=side==='yes'?Math.min(0.99,+(out.price_yes+d).toFixed(4)):Math.max(0.01,+(out.price_yes-d).toFixed(4));out.price_no=+(1-out.price_yes).toFixed(4);};
app.get('/',(req,res)=>res.json({name:'PoneMarket API',version:'1.0.0',mode:'paper_trading',markets:Object.keys(DB.markets).length,agents:Object.keys(DB.agents).length}));
app.post('/v1/agents/register',(req,res)=>{const{name,provider,strategy,starting_balance,webhook_url}=req.body;if(!name||!provider)return res.status(400).json({error:{code:400,type:'BAD_REQUEST',message:'name and provider required.'}});if(!['anthropic','openai','google','custom'].includes(provider))return res.status(400).json({error:{code:400,type:'INVALID_PROVIDER',message:'provider must be: anthropic, openai, google, or custom.'}});const id='agent_'+uuidv4().split('-')[0];const key=apiKey();const bal=Math.max(10,Math.min(100000,starting_balance||1000));DB.agents[id]={agent_id:id,name,provider,strategy:strategy||'',webhook_url:webhook_url||null,api_key:key,balance_usdc:bal,total_invested:0,total_pnl:0,total_trades:0,wins:0,losses:0,status:'active',created_at:new Date().toISOString()};res.status(201).json({agent_id:id,name,provider,api_key:key,balance_usdc:bal,created_at:DB.agents[id].created_at,message:'Save your api_key — shown only once.'});});
app.get('/v1/agents/me',auth,(req,res)=>{const a=req.agent;const rank=Object.values(DB.agents).sort((x,y)=>y.total_pnl-x.total_pnl).findIndex(x=>x.agent_id===a.agent_id)+1;res.json({agent_id:a.agent_id,name:a.name,provider:a.provider,strategy:a.strategy,status:a.status,balance_usdc:+a.balance_usdc.toFixed(2),total_pnl:+a.total_pnl.toFixed(2),total_trades:a.total_trades,win_rate:a.total_trades?+(a.wins/a.total_trades).toFixed(2):null,leaderboard_rank:rank});});
app.post('/v1/agents/webhook',auth,(req,res)=>{if(!req.body.webhook_url)return res.status(400).json({error:{code:400,type:'BAD_REQUEST',message:'webhook_url required.'}});req.agent.webhook_url=req.body.webhook_url;res.json({success:true,webhook_url:req.body.webhook_url});});
app.get('/v1/markets',auth,(req,res)=>{let{category,status='active',limit=20,offset=0,sort='volume'}=req.query;limit=Math.min(+limit,100);offset=+offset;let ms=Object.values(DB.markets);if(category)ms=ms.filter(m=>m.category===category);if(status!=='all')ms=ms.filter(m=>m.status===status);if(sort==='volume')ms.sort((a,b)=>b.volume-a.volume);else if(sort==='newest')ms.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));else if(sort==='closing_soon')ms.sort((a,b)=>new Date(a.closes_at)-new Date(b.closes_at));res.json({markets:ms.slice(offset,offset+limit),total:ms.length,limit,offset});});
app.get('/v1/markets/:id',auth,(req,res)=>{const m=DB.markets[req.params.id];if(!m)return res.status(404).json({error:{code:404,type:'NOT_FOUND',message:'Market not found.'}});res.json(m);});
app.get('/v1/markets/:id/orderbook',auth,(req,res)=>{const m=DB.markets[req.params.id];if(!m)return res.status(404).json({error:{code:404,type:'NOT_FOUND',message:'Market not found.'}});const p=m.outcomes[0].price_yes;res.json({market_id:m.id,outcome_id:m.outcomes[0].id,bids:[{price:+(p-.01).toFixed(2),size:Math.floor(Math.random()*8000+2000)},{price:+(p-.02).toFixed(2),size:Math.floor(Math.random()*15000+5000)}],asks:[{price:+(p+.01).toFixed(2),size:Math.floor(Math.random()*6000+1000)},{price:+(p+.02).toFixed(2),size:Math.floor(Math.random()*12000+3000)}],timestamp:new Date().toISOString()});});
app.post('/v1/orders',auth,(req,res)=>{const{market_id,outcome_id,side,amount,type='market'}=req.body;const a=req.agent;if(!market_id||!outcome_id||!side||!amount)return res.status(400).json({error:{code:400,type:'BAD_REQUEST',message:'market_id, outcome_id, side, amount required.'}});if(!['yes','no'].includes(side))return res.status(400).json({error:{code:400,type:'INVALID_SIDE',message:'side must be yes or no.'}});if(amount<1)return res.status(400).json({error:{code:400,type:'INVALID_AMOUNT',message:'Minimum 1 USDC.'}});const m=DB.markets[market_id];if(!m)return res.status(404).json({error:{code:404,type:'NOT_FOUND',message:'Market not found.'}});if(m.status!=='active')return res.status(422).json({error:{code:422,type:'MARKET_CLOSED',message:'Market already resolved.'}});const out=m.outcomes.find(o=>o.id===outcome_id);if(!out)return res.status(404).json({error:{code:404,type:'NOT_FOUND',message:'Outcome not found.'}});if(a.balance_usdc<amount)return res.status(403).json({error:{code:403,type:'INSUFFICIENT_BALANCE',message:`Balance: ${a.balance_usdc.toFixed(2)} USDC.`}});const fee=+(amount*0.02).toFixed(4);const price=side==='yes'?out.price_yes:out.price_no;const shares=+((amount-fee)/price).toFixed(4);a.balance_usdc-=amount;a.total_invested+=amount;a.total_trades+=1;impact(out,side,amount);m.volume+=amount;const oid='ord_'+uuidv4().split('-')[0];const order={order_id:oid,agent_id:a.agent_id,market_id,market_title:m.title,outcome_id,outcome_label:out.label,side,amount_spent:+amount,shares_received:shares,avg_price:+price.toFixed(4),fee,potential_payout:+shares.toFixed(4),type,status:'filled',pnl:null,result:null,timestamp:new Date().toISOString()};DB.orders[oid]=order;res.status(201).json(order);});
app.get('/v1/orders',auth,(req,res)=>{let{status,market_id,limit=50,offset=0}=req.query;limit=Math.min(+limit,200);offset=+offset;let os=Object.values(DB.orders).filter(o=>o.agent_id===req.agent.agent_id);if(status&&status!=='all')os=os.filter(o=>o.status===status);if(market_id)os=os.filter(o=>o.market_id===market_id);os.sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp));res.json({orders:os.slice(offset,offset+limit),total:os.length});});
app.delete('/v1/orders/:id',auth,(req,res)=>{const o=DB.orders[req.params.id];if(!o)return res.status(404).json({error:{code:404,type:'NOT_FOUND',message:'Order not found.'}});if(o.agent_id!==req.agent.agent_id)return res.status(403).json({error:{code:403,type:'FORBIDDEN',message:'Not your order.'}});if(o.status==='filled')return res.status(422).json({error:{code:422,type:'ALREADY_FILLED',message:'Cannot cancel filled order.'}});o.status='cancelled';req.agent.balance_usdc+=o.amount_spent;res.json({order_id:o.order_id,status:'cancelled'});});
app.get('/v1/portfolio',auth,(req,res)=>{const a=req.agent;const rank=Object.values(DB.agents).sort((x,y)=>y.total_pnl-x.total_pnl).findIndex(x=>x.agent_id===a.agent_id)+1;const open=Object.values(DB.orders).filter(o=>o.agent_id===a.agent_id&&o.pnl===null).length;res.json({agent_id:a.agent_id,balance_usdc:+a.balance_usdc.toFixed(2),total_invested:+a.total_invested.toFixed(2),total_pnl:+a.total_pnl.toFixed(2),pnl_pct:a.total_invested>0?+((a.total_pnl/a.total_invested)*100).toFixed(2):0,win_rate:a.total_trades?+(a.wins/a.total_trades).toFixed(2):null,total_trades:a.total_trades,open_positions:open,leaderboard_rank:rank});});
app.get('/v1/portfolio/positions',auth,(req,res)=>{const positions=Object.values(DB.orders).filter(o=>o.agent_id===req.agent.agent_id&&o.status==='filled'&&o.pnl===null).map(o=>{const m=DB.markets[o.market_id];const out=m?.outcomes.find(x=>x.id===o.outcome_id);const cp=out?(o.side==='yes'?out.price_yes:out.price_no):o.avg_price;return{order_id:o.order_id,market_id:o.market_id,market_title:o.market_title,outcome_label:o.outcome_label,side:o.side,shares:o.shares_received,avg_entry_price:o.avg_price,current_price:+cp.toFixed(4),unrealized_pnl:+(o.shares_received*cp-o.amount_spent).toFixed(2),potential_payout:o.potential_payout};});res.json({positions,total:positions.length});});
app.get('/v1/portfolio/history',auth,(req,res)=>{const trades=Object.values(DB.orders).filter(o=>o.agent_id===req.agent.agent_id&&o.pnl!==null).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp));res.json({trades,total:trades.length});});
app.get('/v1/leaderboard',auth,(req,res)=>{const limit=Math.min(+(req.query.limit||20),100);const board=Object.values(DB.agents).sort((a,b)=>b.total_pnl-a.total_pnl).slice(0,limit).map((a,i)=>({rank:i+1,agent_id:a.agent_id,name:a.name,provider:a.provider,total_pnl:+a.total_pnl.toFixed(2),win_rate:a.total_trades?+(a.wins/a.total_trades).toFixed(2):null,total_trades:a.total_trades}));res.json({leaderboard:board});});
app.post('/v1/admin/resolve',(req,res)=>{const{admin_key,market_id,winning_outcome_id}=req.body;if(admin_key!==(process.env.ADMIN_KEY||'ponemarket_admin_2026'))return res.status(403).json({error:{code:403,type:'FORBIDDEN',message:'Invalid admin key.'}});const m=DB.markets[market_id];if(!m)return res.status(404).json({error:{code:404,type:'NOT_FOUND',message:'Market not found.'}});m.status='resolved';m.resolved_at=new Date().toISOString();m.winning_outcome_id=winning_outcome_id;const affected=Object.values(DB.orders).filter(o=>o.market_id===market_id&&o.pnl===null);affected.forEach(o=>{const won=(o.outcome_id===winning_outcome_id&&o.side==='yes')||(o.outcome_id!==winning_outcome_id&&o.side==='no');const payout=won?o.potential_payout:0;o.pnl=+(payout-o.amount_spent).toFixed(4);o.result=won?'won':'lost';o.payout=payout;const ag=DB.agents[o.agent_id];if(ag){ag.balance_usdc+=payout;ag.total_pnl+=o.pnl;won?ag.wins++:ag.losses++;}});res.json({market_id,status:'resolved',winning_outcome_id,orders_resolved:affected.length});});
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log(`\n  PoneMarket API → http://localhost:${PORT}\n  Markets: ${Object.keys(DB.markets).length} | Mode: Paper Trading\n`));
